### PR TITLE
Can call cli directly from python on command line

### PR DESCRIPTION
**Pull request by cancan101**
This allows me to run the plugin using the CLI by CDing into the plugin directory and then running:

```
PYTHONPATH=~/workspace/xbmcswift2/:$PYTHONPATH python ~/workspace/xbmcswift2/xbmcswift2/cli/cli.py run interactive
```

### CODE REVIEW

**Comment by jbeluch** [comment]
I think this duplicates existing functionality. Look at the setup.py file for xbmcswift2, it has a console script named `xbmcswift2` which does exactly this. Please reopen if I misunderstood what you are attempting to do.

**Comment by cancan101** [comment]
How would I use `setup.py`?

I see:

``` python
    entry_points={
       'console_scripts': [
           'xbmcswift2 = xbmcswift2.cli.cli:main',
       ]
    },
```

**Comment by jbeluch** [comment]
How did you install xbmcswift2? You should be able to just cd into your addon directory and call `xbmcswift2`. Do you have any output from the command `which xbmcswift2`?

**Comment by cancan101** [comment]
Ah. So I never "installed" xbmcswift2. I just manually add it to the `PYTHONPATH` when I want to run my plugin on CLI.

**Comment by jbeluch** [comment]
Ah, ok. Check out http://www.xbmcswift.com/en/latest/installation.html for more info.

However, since you already have the code checked out you can just run `python setup.py install` or just use pip, which will grab the latest released version (corresponds to master branch).

**Comment by cancan101** [comment]
So I intentionally did not install xbmcswift2 that way because I wanted to be able to work on xbmcswift2 as well as my plugin.

When you are developing xbmcswift2 do you keep running `setup.py` on your development code? Or do you run directly against it?

**Comment by jbeluch** [comment]
I have two different virtualenvs, `xbmcswift2` and `xbmcswift2-dev`. The first always has the latest master release installed using pip. This is what I use when developing addons.

If I am working on xbmcswift2 itself, then I use the second virtualenv. I run `python setup.py develop`, which keeps the xbmcswift2 package updated to reflect local changes I make to the code.

**Pull request closed without merging**
