### PR TITLE
only auto call finish if view function return a list

### PR DESCRIPTION
**Pull request by tamland**
As discussed in #72

### CODE REVIEW

**Comment by tamland** [comment]
Let's make that iterable

**Comment by jbeluch** [comment]
Is this still necessary after this fix, https://github.com/jbeluch/xbmcswift2/commit/e004188431510f2f8e844460936d24ea325026ad?

Views will either return lists or None if something went wrong. If set_resolved_url is called, the endOfDirectory call will be skipped due to the above fix. Do you have an example where a view might return something else?

**Comment by tamland** [comment]
What? What does set_resolved_url have to do with this? Views returning None does not mean something went wrong, that's the problem. The same example applies.

**Comment by jbeluch** [comment]
In your example you use plugin.redirect(). You can simply return the result of plugin.redirect. The reason you run into the issue is because you call endOfDirectory yourself.

**Comment by tamland** [comment]
Not sure what you're talking about (again). The original problem I was trying to solve is this: xbmc queries a plugin directory, but the plugin cancels. This is normal, and xbmc stays in current directory. But swift force call endOfDirectory and xbmc goes into an empty directory instead.

**Comment by jbeluch** [comment]
I am confused how this commit https://github.com/jbeluch/xbmcswift2/commit/89d145f205f3135b9ca102f5639ba89fef8c33b6 does not solve your issue then. If your view returns None (a GUI dialog was cancelled for example) then endOfDirectory is called with succeeded=False (this is equivalent to not calling endOfDirectory at all). This keeps XBMC in the current directory and doesn't show an empty directory.

**Comment by tamland** [comment]
Right, _that_ was the problem. I say so in the other thread: it fails on other returns. It force fail on anything you know it isn't going to handle. Actually, current develop branch doesn't work at all now, without this applied. Probably because it currently calls finish no matter what and somebody made a mistake in that function. But that's for another issue I guess..

**Comment by jbeluch** [comment]
What else do your views return besides lists or None? 

The cancelable search functionality that you pointed to as an example can be implemented like so:

``` python
@plugin.route('/search/')
def search():
    query = plugin.keyboard('Enter search term')
    if query:
        return do_the_search(query)

@plugin.route('/search/<query>')
def do_the_search(query):
    return get_items(query)
```

Feel free to give other code samples that are broken.

**Comment by tamland** [comment]
> What else do your views return besides lists or None?

Things besides lists and None. What kind of answer do you expect? A list? I know how to implement the search functionally, that example is exactly the same as the one I pointed to.

But enough talk. The problem is clear: I cant use functions for anything else because swift is force calling and raising exceptions. This makes absolutely no sense. Now decide. I could have implemented wrapper functions for everything by the time spent on this pr.

**Comment by jbeluch** [comment]
> I know how to implement the search functionally, that example is exactly the same as the one I pointed to.

It's not the same, you don't return the result of plugin.redirect(), in your example you return None, which would call finish() indicating an error.

> Things besides lists and None

Then please provide a code sample. I'm tired of arguing over this as well.

**Comment by tamland** [comment]
It wasn't the redirect case that cause any trouble, but the other case.

``` python
@plugin.route('/one'):
def one():
  #plugin stuff
  return 1
```

.. will fail

**Comment by jbeluch** [comment]
In the context of a real addon I don't understand the purpose of returning 1 (or something besides a list or None). It'd be helpful to see real xbmc addon code where this situation occurs. Somewhere in your NRK addon you can point to perhaps?

**Comment by tamland** [comment]
The purpose is reuse, I said this before, and I planed to do it. _1 is an example!_ I'm just trying to be helpful but I really don't have time for this. I'll just write wrapper functions for everything I need to also interface with xbmcswift. What I'm not going to do is write essays about why I want behavior that serves no purpose and does nothing other than hand you an uncatchable exception, removed. Take it or leave it.

**Comment by jbeluch** [comment]
> 1 is an example!

I know, that's why I asked for real code. xbmcswift has an opinionated way of doing things, like returning items from views. I was trying to understand an example when it might be helpful to not assume this but you refrained from showing me any real code.

**Pull request closed without merging**
